import assert from 'node:assert/strict';
import fs from 'node:fs';

const root = new URL('./', import.meta.url);
const read = name => fs.readFileSync(new URL(name, root), 'utf8');
const manifest = JSON.parse(read('manifest.json'));
const content = read('content.js');
const popup = read('popup.html');
const options = read('options.html');
const optionsJs = read('options.js');
const safety = read('safety.js');
assert.equal(manifest.version, '1.0.1');
assert.match(content, /const VERSION = '1\.0\.1'/);
assert.match(content, /<span class="badge">V1\.0<\/span>/);
assert.match(popup, />V1\.0<\/span>/);
assert.match(options, />V1\.0<\/span>/);
assert.doesNotMatch(optionsJs, /leads\/export\.csv\?token=/);
assert.match(optionsJs, /leads\/export\.csv`/);
assert.match(content, /if \(!isVisible\(card\) \|\| isVirtualGhost\(card\)\) return null/);
assert.match(content, /function getVisibleContactScroller\(\)/);
assert.match(content, /isExternalActionStatusCheck\(history\.latestUserMsg\)/);
assert.match(content, /messageAgeDecision\(history\.latestUserTurn\?\.timestamp/);
assert.match(content, /suspendForAuthFailure/);
assert.match(content, /messageRetryUntil\.set\(history\.signature/);
assert.match(content, /开始无人值守/);
assert.match(content, /state\.operatorAway = false/);
assert.match(optionsJs, /saved\.response\.status === 401/);
assert.match(optionsJs, /完整链路通过/);
assert.match(optionsJs, /const escapeHtml =/);
assert.match(optionsJs, /escapeHtml\(data\.reply/);
assert.match(safety, /用户已注销\|账号已注销\|平台系统通知/);

console.log('release contract: ok');
