import assert from 'node:assert/strict';
import fs from 'node:fs';

const root = new URL('./', import.meta.url);
const read = name => fs.readFileSync(new URL(name, root), 'utf8');
const manifest = JSON.parse(read('manifest.json'));
const content = read('content.js');
const popup = read('popup.html');
const options = read('options.html');
const optionsJs = read('options.js');
const safety = read('safety.js');
assert.equal(manifest.version, '1.1.0');
assert.deepEqual(manifest.permissions, ['storage']);
assert.equal(manifest.host_permissions.some(origin => /api\.openai|api\.deepseek|openrouter/.test(origin)), false);
assert.match(content, /const VERSION = '1\.1\.0'/);
assert.match(content, /<span class="badge">V1\.1<\/span>/);
assert.match(popup, />V1\.1<\/span>/);
assert.match(options, />V1\.1<\/span>/);
assert.doesNotMatch(optionsJs, /leads\/export\.csv\?token=/);
assert.match(optionsJs, /leads\/export\.csv`/);
assert.match(content, /if \(!isVisible\(card\) \|\| isVirtualGhost\(card\)\) return null/);
assert.match(content, /function getVisibleContactScroller\(\)/);
assert.match(content, /function ensureMessageWindowAtBottom\(\)/);
assert.match(content, /function isInvertedMessageScroller\(scroller\)/);
assert.match(content, /Safety\.messageBottomState/);
assert.match(content, /function extractMessageTimestamp\(item, bubble\)/);
assert.match(content, /rect\.top >= 80 && rect\.left > window\.innerWidth \* 0\.68/);
assert.doesNotMatch(content, /timestamp: parseTimestamp\(cleanText\(item\.innerText/);
assert.match(content, /ACQUIRE_SEND_LEASE/);
assert.match(content, /isExternalActionStatusCheck\(history\.latestUserMsg\)/);
assert.match(content, /messageAgeDecision\(history\.latestUserTurn\?\.timestamp/);
assert.match(content, /suspendForAuthFailure/);
assert.doesNotMatch(content, /workspaceToken:\s*''\s*}\);\s*syncDockFromState/);
assert.match(content, /'processedMap', 'hourlySendTimestamps', 'uncertainSendMap'/);
assert.match(content, /真实结果未知。安全上必须把它计入小时上限/);
assert.match(content, /messageRetryUntil\.set\(history\.signature/);
assert.match(content, /开始无人值守/);
assert.match(content, /state\.operatorAway = false/);
assert.match(optionsJs, /saved\.response\.status === 401/);
assert.match(optionsJs, /系统没有自动新建工作区/);
assert.doesNotMatch(optionsJs, /saved\.response\.status === 401[^}]+token = await registerWorkspace/s);
assert.match(optionsJs, /完整链路通过/);
assert.match(optionsJs, /Bridge 为开发模式，不建议正式使用/);
assert.match(optionsJs, /本机 Bridge 已就绪 · 安全模式/);
assert.match(optionsJs, /const escapeHtml =/);
assert.match(optionsJs, /escapeHtml\(data\.reply/);
assert.match(safety, /用户已注销\|账号已注销\|平台系统通知/);

console.log('release contract: ok');
